name: Push and Merge Deploy to EC2

on:
  push:
    branches:
      - main  

  pull_request:
    types:
      - closed 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event.pull_request.merged == true)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH
        run: |
            mkdir -p ~/.ssh
            echo "${{secrets.EC2_KEY}}" > id_rsa
            chmod 600 id_rsa
            ssh-keyscan -H ${{secrets.EC2_HOST}} >> ~/.ssh/known_hosts
      - name: Deploy to EC2
        run: |
            scp -i id_rsa -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html
      - name: "Installing Php Depentancies"
        run: |
            ssh -i id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /var/www/html && composer install"

        

  